[build-system] 
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
 
[project]
name = "asahi" 
version = "0.1"
authors = [
]
description = ""
readme = "" 
requires-python = ">=3.9"
classifiers = [
]
 
[project.urls] 
"Homepage" = "" 
