[build-system] 
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
 
[project]
name = "asahi" 
version = "0.1"
authors = [
]
requires-python = ">=3.9"
dependencies=[
    "boto3", 
    "botocore",
    "aiohttp",
    "lxml"
]
[project.urls] 
"Homepage" = "" 
